server:
  port: 80
  error:
    include-message: always
    include-binding-errors: always
    path: /error

spring:
  mvc:
    async:
      request-timeout: 720000

datasource:
  url: jdbc:h2:mem:testdb
  username: sa
  password:

h2:
  console:
    enabled: true
    path: /h2-console
  jpa:
    open-in-view: false